/**
 * Generator for the state-code normalization migration (DEV.33, Stage C C.2).
 *
 * Produces — by iterating the canonical INDIAN_STATES map in
 * `@dealerlink/schemas` so all 36 states/UTs are covered with no hand-typed
 * CASE arms — two SQL artefacts:
 *
 *   1. The FORWARD data block (`*.generated.sql`): per-column UPDATEs that map
 *      full state names (any case) to ISO 3166-2:IN 2-letter codes, plus
 *      blank→NULL fixups for the nullable columns. This block is pasted into
 *      the head of the drizzle-generated migration (the constraint-tightening
 *      DDL is produced by `drizzle-kit generate`); the UPDATEs MUST run before
 *      the tighter CHECKs are added, so they sit at the top of the file.
 *
 *   2. The REVERSIBLE rollback (`migrations/rollback/*.sql`): maps codes back
 *      to canonical full names and restores the loose `length(...) >= 2`
 *      constraints. Applied manually if a staging deploy must revert.
 *
 * Run: pnpm --filter @dealerlink/db exec tsx scripts/generate-state-migration.ts
 *
 * It writes files; it does not touch the database. Re-running is idempotent.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { INDIAN_STATES, INDIAN_STATE_CODES, type IndianStateCode } from '@dealerlink/schemas';

const here =
  typeof __dirname !== 'undefined' ? __dirname : path.dirname(fileURLToPath(import.meta.url));
const migrationsDir = path.resolve(here, '../migrations');
const rollbackDir = path.resolve(migrationsDir, 'rollback');

const BREAK = '\n--> statement-breakpoint\n';

const ROLLBACK_NAME = '0015_normalize_state_codes_rollback.sql';
const FORWARD_NAME = '0015_normalize_state_codes.data.generated.sql';

/** Every column that stores an Indian state. `dispatches` has none (it inherits via the order). */
const STATE_COLUMNS: ReadonlyArray<{ table: string; column: string; nullable: boolean }> = [
  { table: 'tenant_settings', column: 'state', nullable: true },
  { table: 'tenant_settings', column: 'address_state', nullable: true },
  { table: 'dealers', column: 'state', nullable: true },
  { table: 'quotations', column: 'tenant_state_at_issue', nullable: false },
  { table: 'quotations', column: 'place_of_supply', nullable: false },
  { table: 'performa_invoices', column: 'tenant_state_at_issue', nullable: false },
  { table: 'performa_invoices', column: 'place_of_supply', nullable: false },
  { table: 'orders', column: 'tenant_state_at_issue', nullable: false },
  { table: 'orders', column: 'place_of_supply', nullable: false },
];

const sqlStr = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** Forward: name (any case) → code. Case-insensitive match on UPPER(BTRIM(col)). */
function forwardUpdate({ table, column, nullable }: (typeof STATE_COLUMNS)[number]): string {
  const arms = INDIAN_STATE_CODES.map(
    (code) => `    WHEN ${sqlStr(INDIAN_STATES[code].toUpperCase())} THEN ${sqlStr(code)}`,
  ).join('\n');
  const update = `UPDATE "${table}" SET "${column}" = (
  CASE upper(btrim("${column}"))
${arms}
    ELSE upper(btrim("${column}"))
  END
) WHERE "${column}" IS NOT NULL AND btrim("${column}") <> '';`;
  if (!nullable) return update;
  // Nullable columns: collapse blanks to NULL so the new CHECK is satisfied.
  const blank = `UPDATE "${table}" SET "${column}" = NULL WHERE "${column}" IS NOT NULL AND btrim("${column}") = '';`;
  return `${update}${BREAK}${blank}`;
}

/** Rollback: code → canonical full name. */
function rollbackUpdate({ table, column }: (typeof STATE_COLUMNS)[number]): string {
  const arms = (INDIAN_STATE_CODES as IndianStateCode[])
    .map((code) => `    WHEN ${sqlStr(code)} THEN ${sqlStr(INDIAN_STATES[code])}`)
    .join('\n');
  return `UPDATE "${table}" SET "${column}" = (
  CASE "${column}"
${arms}
    ELSE "${column}"
  END
) WHERE "${column}" IS NOT NULL;`;
}

// --- Forward data block ------------------------------------------------------
const forwardHeader = `-- GENERATED by scripts/generate-state-migration.ts — do not edit by hand.
-- Phase 1 of the state-code normalization (DEV.33). Normalises every state
-- column from full names to ISO 3166-2:IN codes. Runs inside the migration
-- transaction BEFORE the tightened CHECK constraints are added.`;
const forwardBody = STATE_COLUMNS.map(forwardUpdate).join(BREAK);
const forwardSql = `${forwardHeader}\n${forwardBody}`;

// --- Rollback ----------------------------------------------------------------
const looseChecks = [
  ['quotations', 'quotations_state_codes_chk'],
  ['performa_invoices', 'performa_invoices_state_codes_chk'],
  ['orders', 'orders_state_codes_chk'],
] as const;
const rollbackDdl = [
  ...looseChecks.flatMap(([table, name]) => [
    `ALTER TABLE "${table}" DROP CONSTRAINT IF EXISTS "${name}";`,
    `ALTER TABLE "${table}" ADD CONSTRAINT "${name}" CHECK (length("tenant_state_at_issue") >= 2 AND length("place_of_supply") >= 2);`,
  ]),
  `ALTER TABLE "dealers" DROP CONSTRAINT IF EXISTS "dealers_state_chk";`,
  `ALTER TABLE "tenant_settings" DROP CONSTRAINT IF EXISTS "tenant_settings_state_chk";`,
  `ALTER TABLE "tenant_settings" DROP CONSTRAINT IF EXISTS "tenant_settings_address_state_chk";`,
].join('\n');

const rollbackSql = `-- GENERATED by scripts/generate-state-migration.ts — do not edit by hand.
-- ROLLBACK for the state-code normalization (DEV.33, Stage C Day C.2).
--
-- Reverses the forward migration: maps ISO 3166-2:IN codes back to canonical
-- full names and restores the loose length(...) >= 2 constraints. Apply only
-- if a deploy must revert. Note: case is NOT restored (all states come back as
-- canonical title-case names) — semantically equivalent, since inter/intra is
-- decided by equality within a single row.
--
-- Run manually:  psql "$DATABASE_DIRECT_URL" -f migrations/rollback/${ROLLBACK_NAME}
--
BEGIN;
${STATE_COLUMNS.map(rollbackUpdate).join('\n\n')}

${rollbackDdl}
COMMIT;
`;

// Both generated artefacts live under migrations/rollback/ — a directory the
// drizzle migrator does NOT scan (it only runs tags listed in meta/_journal).
// The forward block is pasted into the head of the journaled migration; this
// copy is kept for review + re-verification.
fs.mkdirSync(rollbackDir, { recursive: true });
fs.writeFileSync(path.join(rollbackDir, FORWARD_NAME), `${forwardSql}\n`, 'utf8');
fs.writeFileSync(path.join(rollbackDir, ROLLBACK_NAME), rollbackSql, 'utf8');

console.log(`✓ Forward data block  → migrations/rollback/${FORWARD_NAME}`);
console.log(`✓ Rollback script     → migrations/rollback/${ROLLBACK_NAME}`);
console.log(
  `  Covered ${INDIAN_STATE_CODES.length} states across ${STATE_COLUMNS.length} columns.`,
);
console.log('\n--- forward data block (paste at top of the drizzle migration) ---\n');
console.log(forwardSql);
